### ISSUE TITLE
[feat] Create Issue & PR template

### ISSUE THREAD

**Issue by geeneve** [TeamBookTez/booktez-server#106]
## 💡 Issue
- 이슈 템플릿 생성
- PR 템플릿 생성

## 📝 todo
- [ ] FEAT 이슈 템플릿 수정
- [ ] FIX 이슈 템플릿 수정
- [ ] REFACTOR 이슈 템플릿 생성
- [ ] PR 템플릿 생성
