### ISSUE TITLE
[feat] sign up api 생성

### ISSUE THREAD

**Issue by geeneve** [TeamBookTez/booktez-server#11]
## 💡 Issue
- auth 라우터의 signup api 생성

## 📝 todo
- [ ] email, password null check
- [ ] email 형식 확인
- [ ] email, 닉네임 중복 확인
