### ISSUE TITLE
[bug] fix signup

### ISSUE THREAD

**Issue by geeneve** [TeamBookTez/booktez-server#16]
## 🐞 버그 설명
- 탈퇴한 회원 쿼리문 수정
- 한글 닉네임 허용

## 📝 todo
- [x] import에 주석 달기
- [ ] find 쿼리에 is_deleted 확인
- [x] 한글 닉네임도 가능하도록 변경
