### ISSUE TITLE
[bug] fix login

### ISSUE THREAD

**Issue by seohyun-106** [TeamBookTez/booktez-server#17]
## 🐞 버그 설명
- 탈퇴된 회원 쿼리문 수정

## 📝 todo
- [x] #18
- [x] Controller 파라미터 req.body 한번에 보내도록
- [x] Controller reponseData 네이밍 data -> resData
- [x] 불필요한 변수선언 제거
- [x] 프리티어 적용 확인
- [x] Service 오류코드 constant library 적용
- [ ] isDeleted 체크
