### ISSUE TITLE
[feat] feat nickname api

### ISSUE THREAD

**Issue by seohyun-106** [TeamBookTez/booktez-server#49]
## 💡 Issue
- 이메일 유효성 검사 api 추가

## 📝 todo
- [ ] email null check
- [ ] 형식에 맞는지 검사
- [ ] 중복 이메일 검사
