### ISSUE TITLE
[fix] add isDeleted to User.find

### ISSUE THREAD

**Issue by geeneve** [TeamBookTez/booktez-server#57]
## 🐞 변경 사항 설명
- 시퀄라이즈 구조 변경에 따른 코드 수정

## 📝 todo
- [ ] 시퀄라이즈 Column 이름 변경에 따른 코드 수정
- [ ] User.find에 isDeleted 항목 추가
- [ ] 스네이크 케이스로 되어 있는 코드 카멜 케이스로 변경
