### ISSUE TITLE
[fix] change request of check email, nickname body to params

### ISSUE THREAD

**Issue by geeneve** [TeamBookTez/booktez-server#58]
## 🐞 수정 사항
- `/auth/email` `/auth/nickname` api의 request가 body로 전달 받던 것을 param으로 변경

## 📝 todo
- [x] `/auth/email` 수정
- [x] `/auth/nickname` 수정
- [x]  api docs 수정
