### ISSUE TITLE
[fix] api response body 수정사항

### ISSUE THREAD

**Issue by seohyun-106** [TeamBookTez/booktez-server#68]
## 🐞 버그 설명
get/review, get/book response body에 변경사항이 생겼슴다

## 📝 todo
- [x] Book DB에 출간일, 엮은이 column 추가
- [x] patch/review response에 책 상세정보 추가
- [x] get/book response에 reviewId 추가
- [ ] post/book translator, publicationDate 관련 수정"
- [x] API 명세서 수정
