### ISSUE TITLE
[fix] change variable (column) name

### ISSUE THREAD

**Issue by geeneve** [TeamBookTez/booktez-server#91]
## 🐞 버그 설명
- 통일되지 않았던 여러 변수들을 하나로 바꾸어 통일성 있게 수정
  - EX) `progress` -> `reviewSt`
  - `publicationDate` -> `publicationDt` 

## 📝 todo
- [x] POST /book 수정
- [x] PATCH /review/:reviewId/pre 수정
- [x] PATCH /review/:reviewId/peri 수정
- [x] GET /review/:reviewId 수정
- [x] 노션 댓글 최신화
